name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  table_calendar: ^3.0.9 
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.0
  http: ^1.2.1
  auth_email: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#FFFFFF"


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/RoomD.png
    - assets/images/background.jpg
    - assets/images/offer1.png
    - assets/images/offer2.png
    - assets/images/offer3.png
    - assets/images/room1.png
    - assets/images/room2.png
    - assets/images/room3.png
    - assets/images/room4.png
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/shape_bg1.png
    - assets/images/shape_bg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
